### PR TITLE
feat: add getObjectInfos to allowed usage list

### PR DESCRIPTION
**Pull request by yungcheng**

### CODE REVIEW

**Comment by kevinv11n** [comment]
@apapko  @Gr8Gatsby what's the branching strategy for this repo for features coming in the next major release? This PR is applicable only to the 228 / Winter 21 release.

**Comment by pmdartus** [comment]
@yungcheng @kevinv11n We have not enabled this on the server for 228 and it won't also be enabled for 230. It should be fine merging this right now.

Is this PR still valid? I am preparing a new release of this package.

**Comment by yungcheng** [comment]
> @yungcheng @kevinv11n We have not enabled this on the server for 228 and it won't also be enabled for 230. It should be fine merging this right now.
> 
> Is this PR still valid? I am preparing a new release of this package.

It is still valid and would be great if you can merge it

**Comment by kevinv11n** [comment]
Yes, please merge. This should've gone out with 228.

**Comment by pmdartus** [comment]
It has been published with the V0.8.0 release.

**Pull request merged**
